#ifndef _SMARTRF_SETTINGS_15_4G_11_H_
#define _SMARTRF_SETTINGS_15_4G_11_H_

//*********************************************************************************
// Generated by SmartRF Studio version 2.27.0 (build#362)
// The applied template is compatible with cc13x2_26x2 SDK version 2.30.xx.xx or newer.
// Device: CC1352P7 Rev. B (1.1). Only supported by CC26x2 SDK version 5.10.xx.xx or newer
//
//*********************************************************************************
#include <ti/devices/DeviceFamily.h>
#include DeviceFamily_constructPath(driverlib/rf_mailbox.h)
#include DeviceFamily_constructPath(driverlib/rf_common_cmd.h)
#include DeviceFamily_constructPath(driverlib/rf_prop_cmd.h)
#include <ti/drivers/rf/RF.h>


// TI-RTOS RF Mode Object
extern RF_Mode Ieee154g11_mode;

// RF Core API Commands
extern rfc_CMD_PROP_RADIO_DIV_SETUP_PA_t Ieee154g11_cmdPropRadioDivSetup;
extern rfc_CMD_FS_t Ieee154g11_cmdFs;
extern rfc_CMD_PROP_TX_ADV_t Ieee154g11_cmdPropTxAdv;
extern rfc_CMD_PROP_RX_ADV_t Ieee154g11_cmdPropRxAdv;

// RF Core API Overrides
extern uint32_t Ieee154g11_pOverrides[];
extern uint32_t Ieee154g11_pOverridesTxStd[];
extern uint32_t Ieee154g11_pOverridesTx20[];

#endif // _SMARTRF_SETTINGS_15_4G_11_H_
