#ifndef _SMARTRF_SETTINGS_15_4G_5_H__
#define _SMARTRF_SETTINGS_15_4G_5_H__

//*********************************************************************************
// Generated by SmartRF Studio version 2.7.0 (build #21)
// Tested for SimpleLink SDK version: CC13x0 SDK 1.50.xx.xx
// Device: CC1350 Rev. 2.1
// 
//*********************************************************************************
#include <ti/devices/DeviceFamily.h>
#include DeviceFamily_constructPath(driverlib/rf_mailbox.h)
#include DeviceFamily_constructPath(driverlib/rf_common_cmd.h)
#include DeviceFamily_constructPath(driverlib/rf_prop_cmd.h)
#include <ti/drivers/rf/RF.h>


// TI-RTOS RF Mode Object
extern RF_Mode Ieee154g5_mode;


// RF Core API commands
extern rfc_CMD_PROP_RADIO_DIV_SETUP_t Ieee154g5_cmdPropRadioDivSetup;
extern rfc_CMD_FS_t Ieee154g5_cmdFs;
extern rfc_CMD_PROP_TX_t Ieee154g5_cmdPropTx;
extern rfc_CMD_PROP_RX_t Ieee154g5_cmdPropRx;
extern rfc_CMD_PROP_RX_ADV_t Ieee154g5_cmdPropRxAdv;
extern rfc_CMD_PROP_TX_ADV_t Ieee154g5_cmdPropTxAdv;


#endif // _SMARTRF_SETTINGS_15_4G_5_H__

