blank_issues_enabled: false
contact_links:
  - name: See if your issue is solved before creating a new one.
    about: Try to see if ther is an answer for yoru questions before you create a new issue.
    url: https://github.com/ElectronicCats/CatSniffer/issues?q=is%3Aissue+is%3Aclosed
  - name: ElectronicCats
    about: Contact us through our website
    url: https://electroniccats.com/contact/