#ifndef _SMARTRF_SETTINGS_WBMS_0_H_
#define _SMARTRF_SETTINGS_WBMS_0_H_

//*********************************************************************************
// Generated by SmartRF Studio version 2.15.0 (build #193 a2)
// This file has been modified from the original (2640R2) exported version
// Device: CC2652R2
//
//*********************************************************************************

#include <ti/devices/DeviceFamily.h>
#include DeviceFamily_constructPath(driverlib/rf_mailbox.h)
#include DeviceFamily_constructPath(driverlib/rf_common_cmd.h)
#include DeviceFamily_constructPath(driverlib/rf_ble_cmd.h)
#include <ti/drivers/rf/RF.h>


// TI-RTOS RF Mode Object
extern RF_Mode Wbms0_mode;

// RF Core API commands
extern rfc_CMD_BLE5_RADIO_SETUP_t Wbms0_cmdBle5RadioSetup;
extern rfc_CMD_FS_t Wbms0_cmdFs;
extern rfc_CMD_PROP_TX_ADV_t Wbms0_cmdPropTxAdv;
extern rfc_CMD_PROP_RX_ADV_t Wbms0_cmdPropRxAdv;

#endif // _SMARTRF_SETTINGS_WBMS_0_H_
